### PR TITLE
Rewrite web interface replacing NanoHTTPD in favor of Javalin. Fixes #1

### LINKED ISSUE #1: Switch out NanoHTTPD and websockets in favor of Javalin
The current implementation works fine, but I didn't really do much research on what was available and well maintained. It looks like NanoHTTPD is abandonware which is not a good sign. 

After a bit more research it seems that [Javalin](https://javalin.io) would be a much better choice as it can consolidate both the server and websockets.

### PR DESCRIPTION
**Pull request by creesch**
Alright, actually got it working. Fixes #1 

Replaces NanoHTTPD in favor of javalin giving a cleaner and more modern implementation.

### CODE REVIEW

**Comment by creesch** [comment]
Aaaand build is broken again... not sure what is going on with dependencies here.

**Comment by danthedaniel** [comment]
Does this obsolete #12?

**Comment by creesch** [comment]
Alright... threw away `.gradle` entirely in my home directory and now it builds again locally. Let's double check if artifacts also contain proper builds...

**Comment by creesch** [comment]
Alright, took some work but finally got it working properly using the shadow plugin.

**Pull request merged**
